# Generated by Django 5.2.17 on 2026-09-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_loginthrottle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('SUBMITTED', 'ثبت\u200cشده'), ('UNDER_REVIEW', 'در حال بررسی'), ('NEED_INFO', 'نیازمند اطلاعات تکمیلی'), ('ACCEPTED', 'پذیرفته\u200cشده'), ('IN_PROGRESS', 'در حال انجام'), ('ON_HOLD', 'متوقف\u200cشده'), ('COMPLETED', 'تکمیل\u200cشده'), ('REJECTED', 'ردشده'), ('CANCELLED', 'لغوشده')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
