# Generated by Django 5.2.17 on 2026-10-01 22:35

import portal.appearance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_department_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(default='مرکز خدمات راهکارهای هوشمند', max_length=100)),
                ('primary_color', models.CharField(default='#1764a5', max_length=7, validators=[portal.appearance.validate_brand_color])),
                ('accent_color', models.CharField(default='#0d786c', max_length=7, validators=[portal.appearance.validate_brand_color])),
                ('base_font_size', models.PositiveSmallIntegerField(choices=[(14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')], default=15)),
                ('font_family', models.CharField(choices=[('system', 'قلم سامانه'), ('tahoma', 'Tahoma'), ('arial', 'Arial')], default='system', max_length=16)),
                ('logo', models.FileField(blank=True, upload_to=portal.appearance.brand_logo_path, validators=[portal.appearance.validate_png_logo])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
