# Generated by Django 5.2.17 on 2026-10-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_appearancesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('ACTIVE', 'فعال'), ('DISABLED', 'غیرفعال'), ('ARCHIVED', 'بایگانی\u200cشده')], db_index=True, default='DRAFT', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('ACTIVE', 'فعال'), ('DISABLED', 'غیرفعال'), ('ARCHIVED', 'بایگانی\u200cشده')], db_index=True, default='DRAFT', max_length=16)),
            ],
            options={
                'ordering': ['program__name', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='role_assignment_scope_target',
        ),
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='role_assignment_role_scope',
        ),
        migrations.AddField(
            model_name='request',
            name='program_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='request',
            name='program_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='project_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='request',
            name='project_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='requester_role_at_submission',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='request',
            name='requester_role_context',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'درخواست\u200cدهنده'), ('REQUEST_MANAGER', 'مدیر درخواست'), ('DEPARTMENT_LEAD', 'مدیر اداره'), ('SUPERVISOR', 'ناظر'), ('EXECUTIVE_VIEWER', 'مشاهده\u200cگر ارشد'), ('SUPER_ADMIN', 'مدیر ارشد سامانه'), ('PROGRAM_MANAGER', 'مدیر طرح'), ('PROJECT_MANAGER', 'مدیر پروژه')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='scope_type',
            field=models.CharField(choices=[('GLOBAL', 'سراسری'), ('DEPARTMENT', 'اداره'), ('PROGRAM', 'طرح'), ('PROJECT', 'پروژه')], db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['status', 'code'], name='portal_prog_status_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED'])), name='valid_program_status'),
        ),
        migrations.AddField(
            model_name='request',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='portal.program'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='portal.program'),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='portal.program'),
        ),
        migrations.AddField(
            model_name='request',
            name='project_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='portal.project'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='portal.project'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['program', 'status'], name='portal_requ_program_status_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['project_entity', 'status'], name='portal_requ_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'role', 'program', 'is_active'], name='portal_role_prog_active_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'role', 'project', 'is_active'], name='portal_role_proj_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('program__isnull', True), ('project__isnull', True), ('scope_type', 'GLOBAL')), models.Q(('department__isnull', False), ('program__isnull', True), ('project__isnull', True), ('scope_type', 'DEPARTMENT')), models.Q(('department__isnull', True), ('program__isnull', False), ('project__isnull', True), ('scope_type', 'PROGRAM')), models.Q(('department__isnull', True), ('program__isnull', False), ('project__isnull', False), ('scope_type', 'PROJECT')), _connector='OR'), name='role_assignment_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['REQUESTER', 'SUPERVISOR', 'EXECUTIVE_VIEWER', 'SUPER_ADMIN']), ('scope_type', 'GLOBAL')), models.Q(('role__in', ['REQUEST_MANAGER', 'DEPARTMENT_LEAD']), ('scope_type', 'DEPARTMENT')), models.Q(('role', 'PROGRAM_MANAGER'), ('scope_type', 'PROGRAM')), models.Q(('role', 'PROJECT_MANAGER'), ('scope_type', 'PROJECT')), _connector='OR'), name='role_assignment_role_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'PROGRAM')), fields=('user', 'role', 'program'), name='unique_program_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'PROJECT')), fields=('user', 'role', 'project'), name='unique_project_role_assignment'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['program', 'status'], name='portal_proj_prog_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED'])), name='valid_project_status'),
        ),
    ]
