# Generated by Django 5.2.17 on 2026-10-02 14:55

import django.db.models.deletion
import django.utils.timezone
import portal.models
from django.conf import settings
from django.db import migrations, models


def seed_governance(apps, schema_editor):
    Priority = apps.get_model('portal', 'PriorityPolicy')
    Policy = apps.get_model('portal', 'ApprovalPolicy')
    Config = apps.get_model('portal', 'SeniorApprovalConfiguration')
    for code, name, order, credit, approval, tone in (
        ('NORMAL', 'عادی', 10, False, False, 'neutral'),
        ('HIGH', 'زیاد', 20, False, False, 'warning'),
        ('VERY_URGENT', 'خیلی فوری', 30, True, True, 'warning'),
        ('EMERGENCY', 'اضطراری', 40, True, True, 'critical'),
    ):
        priority, _ = Priority.objects.get_or_create(code=code, defaults={
            'name': name, 'display_order': order, 'requires_credit': credit,
            'requires_approval': approval, 'semantic_tone': tone})
        if approval:
            Policy.objects.get_or_create(trigger='PRIORITY', priority=priority,
                requester_role='PROJECT_MANAGER', target='PROGRAM_MANAGER', sequence=1,
                defaults={'name': f'{name} · تأیید مدیر طرح', 'pauses_sla': True})
    for target, name in (('PROGRAM_MANAGER','تأیید مدیر طرح'),('SENIOR','تأیید مرجع ارشد')):
        Policy.objects.get_or_create(trigger='PROVIDER', target=target, sequence=1,
            defaults={'name': name, 'pauses_sla': True})
    Config.objects.get_or_create(pk=1, defaults={'title':'مرجع تأیید ارشد','is_active':True})


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_program_project_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('MONTH', 'ماهانه'), ('QUARTER', 'فصلی'), ('HALF_YEAR', 'شش\u200cماهه'), ('YEAR', 'سالانه'), ('CUSTOM', 'سفارشی')], max_length=12)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=portal.models.approval_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('PRIORITY', 'اولویت درخواست'), ('PROVIDER', 'ارجاع ارائه\u200cدهنده')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تأییدشده'), ('REJECTED', 'ردشده'), ('CLARIFICATION_REQUESTED', 'نیازمند توضیح'), ('CANCELLED', 'لغوشده')], db_index=True, default='PENDING', max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('estimated_time', models.CharField(blank=True, max_length=120)),
                ('estimated_cost', models.CharField(blank=True, max_length=120)),
                ('conditions', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('context_snapshot', models.JSONField(default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('APPROVED', 'تأیید'), ('REJECTED', 'رد'), ('CLARIFICATION_REQUESTED', 'درخواست توضیح'), ('AUTO_APPROVED', 'تأیید خودکار')], max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('trigger', models.CharField(choices=[('PRIORITY', 'اولویت درخواست'), ('PROVIDER', 'ارجاع ارائه\u200cدهنده')], max_length=12)),
                ('requester_role', models.CharField(blank=True, default='', max_length=32)),
                ('target', models.CharField(choices=[('PROGRAM_MANAGER', 'مدیر طرح'), ('SENIOR', 'مرجع ارشد')], max_length=20)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('pauses_sla', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('target', models.CharField(choices=[('PROGRAM_MANAGER', 'مدیر طرح'), ('SENIOR', 'مرجع ارشد')], max_length=20)),
                ('status', models.CharField(choices=[('BLOCKED', 'در صف'), ('PENDING', 'در انتظار'), ('APPROVED', 'تأییدشده'), ('REJECTED', 'ردشده'), ('CLARIFICATION_REQUESTED', 'نیازمند توضیح'), ('CANCELLED', 'لغوشده')], db_index=True, default='BLOCKED', max_length=24)),
                ('pauses_sla', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('target_snapshot', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreditAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('RESERVE', 'رزرو'), ('CONSUME', 'مصرف'), ('RELEASE', 'آزادسازی')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CreditReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RESERVED', 'رزروشده'), ('CONSUMED', 'مصرف\u200cشده'), ('RELEASED', 'آزادشده')], default='RESERVED', max_length=10)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriorityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('LOW', 'کم'), ('NORMAL', 'عادی'), ('HIGH', 'زیاد'), ('URGENT', 'فوری'), ('VERY_URGENT', 'خیلی فوری'), ('EMERGENCY', 'اضطراری')], max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_credit', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('semantic_tone', models.CharField(choices=[('neutral', 'عادی'), ('warning', 'هشدار'), ('critical', 'بحرانی')], default='neutral', max_length=16)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeniorApprovalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='مرجع تأیید ارشد', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='role_assignment_role_scope',
        ),
        migrations.AddField(
            model_name='request',
            name='provider_hold',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('LOW', 'کم'), ('NORMAL', 'عادی'), ('HIGH', 'زیاد'), ('URGENT', 'فوری'), ('VERY_URGENT', 'خیلی فوری'), ('EMERGENCY', 'اضطراری')], default='NORMAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'درخواست\u200cدهنده'), ('REQUEST_MANAGER', 'مدیر درخواست'), ('DEPARTMENT_LEAD', 'مدیر اداره'), ('SUPERVISOR', 'ناظر'), ('EXECUTIVE_VIEWER', 'مشاهده\u200cگر ارشد'), ('SUPER_ADMIN', 'مدیر ارشد سامانه'), ('PROGRAM_MANAGER', 'مدیر طرح'), ('PROJECT_MANAGER', 'مدیر پروژه'), ('SENIOR_APPROVAL_AUTHORITY', 'مرجع تأیید ارشد')], db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['REQUESTER', 'SUPERVISOR', 'EXECUTIVE_VIEWER', 'SUPER_ADMIN', 'SENIOR_APPROVAL_AUTHORITY']), ('scope_type', 'GLOBAL')), models.Q(('role__in', ['REQUEST_MANAGER', 'DEPARTMENT_LEAD']), ('scope_type', 'DEPARTMENT')), models.Q(('role', 'PROGRAM_MANAGER'), ('scope_type', 'PROGRAM')), models.Q(('role', 'PROJECT_MANAGER'), ('scope_type', 'PROJECT')), _connector='OR'), name='role_assignment_role_scope'),
        ),
        migrations.AddField(
            model_name='approvalattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalcase',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_cases', to='portal.request'),
        ),
        migrations.AddField(
            model_name='approvalcase',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalattachment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='portal.approvalcase'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='portal.approvalcase'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='decided_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.approvalpolicy'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='portal.request'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='portal.approvalstep'),
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='portal.department'),
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='portal.allocationperiod'),
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='portal.program'),
        ),
        migrations.AddField(
            model_name='creditledgerentry',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditreservation',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='portal.creditallocation'),
        ),
        migrations.AddField(
            model_name='creditreservation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_reservation', to='portal.request'),
        ),
        migrations.AddField(
            model_name='creditledgerentry',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='portal.creditreservation'),
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='portal.prioritypolicy'),
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.prioritypolicy'),
        ),
        migrations.AddIndex(
            model_name='approvalcase',
            index=models.Index(fields=['request', 'trigger', 'status'], name='approval_case_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('case', 'sequence'), name='unique_approval_case_step'),
        ),
        migrations.AddConstraint(
            model_name='creditledgerentry',
            constraint=models.UniqueConstraint(fields=('reservation', 'event'), name='unique_credit_transition'),
        ),
        migrations.AddIndex(
            model_name='creditallocation',
            index=models.Index(fields=['program', 'department', 'priority', 'is_active'], name='credit_wallet_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditallocation',
            constraint=models.UniqueConstraint(fields=('program', 'department', 'priority', 'period'), name='unique_credit_wallet'),
        ),
        migrations.CreateModel(
            name='ApprovalClarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarifications', to='portal.approvalcase')),
            ],
        ),
        migrations.RunPython(seed_governance, migrations.RunPython.noop),
    ]
