# Generated by Django 5.2.17 on 2026-10-02 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_lifecycle_and_request_snapshots(apps, schema_editor):
    Category=apps.get_model('portal','Category')
    Service=apps.get_model('portal','Service')
    Request=apps.get_model('portal','Request')
    Category.objects.filter(active=False).update(lifecycle_status='DISABLED')
    Service.objects.filter(active=False).update(lifecycle_status='DISABLED')
    db=schema_editor.connection.alias
    pending=[]
    for req in Request.objects.using(db).select_related('service__category__department').prefetch_related('service__form_fields').iterator(chunk_size=500):
        if req.catalogue_snapshot or not req.service_id: continue
        service=req.service
        fields=[{'key':f.key,'label':f.label,'field_type':f.field_type,'required':f.required,'options':f.options,'placeholder':f.placeholder,'help_text':f.help_text,'display_order':f.display_order} for f in service.form_fields.all()]
        req.catalogue_snapshot={'service_code':service.code,'service_name':service.name,'department_code':service.category.department.code,
            'department_name':service.category.department.name,'family_name':service.category.name,
            'service':{key:getattr(service,key) for key in ('domain','short_description','full_description','purpose','scope','deliverables','required_inputs','request_requirements','process_information','excluded','service_role','acceptance_criteria','legacy_sla','initial_response_days','review_target_days','delivery_min_days','delivery_max_days','maximum_duration_days','supports_desired_date')},
            'form_fields':fields}
        pending.append(req)
        if len(pending)>=500:
            Request.objects.using(db).bulk_update(pending,['catalogue_snapshot']);pending=[]
    if pending:Request.objects.using(db).bulk_update(pending,['catalogue_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_priority_capacity_approval_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PREVIEWED', 'پیش\u200cنمایش'), ('CONFIRMED', 'تأییدشده'), ('FAILED', 'ناموفق')], default='PREVIEWED', max_length=12)),
                ('validation_result', models.JSONField(blank=True, default=dict)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='valid_department_status',
        ),
        migrations.AddField(
            model_name='category',
            name='lifecycle_status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('DISABLED', 'غیرفعال'), ('ARCHIVED', 'بایگانی\u200cشده')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='department',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='departments/covers/'),
        ),
        migrations.AddField(
            model_name='department',
            name='icon_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='catalogue_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='lifecycle_status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('DISABLED', 'غیرفعال'), ('ARCHIVED', 'بایگانی\u200cشده')], default='ACTIVE', max_length=12),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشرشده'), ('DISABLED', 'غیرفعال'), ('TEMPORARILY_DISABLED', 'موقتاً غیرفعال'), ('ARCHIVED', 'بایگانی\u200cشده')], db_index=True, default='DRAFT', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PUBLISHED', 'DISABLED', 'TEMPORARILY_DISABLED', 'ARCHIVED'])), name='valid_department_status'),
        ),
        migrations.AddField(
            model_name='catalogueimportbatch',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_catalogue_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogueimportbatch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_imports', to='portal.department'),
        ),
        migrations.AddField(
            model_name='catalogueimportbatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_lifecycle_and_request_snapshots,migrations.RunPython.noop),
    ]
