# Generated by Django 5.2.17 on 2026-10-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_catalogue_scaling_2_4'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle_status__in', ['ACTIVE', 'DISABLED', 'ARCHIVED'])), name='valid_category_lifecycle'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle_status__in', ['ACTIVE', 'DISABLED', 'ARCHIVED'])), name='valid_service_lifecycle'),
        ),
    ]
