# Generated by Django 5.2.17 on 2026-10-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_catalogue_lifecycle_constraints_2_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'متن کوتاه'), ('textarea', 'متن بلند'), ('number', 'عدد'), ('date', 'تاریخ'), ('select', 'انتخاب'), ('radio', 'گزینه\u200cهای رادیویی'), ('multiselect', 'چندانتخابی'), ('checkbox', 'تأیید'), ('email', 'ایمیل'), ('phone', 'تلفن'), ('file', 'فایل')], max_length=20),
        ),
    ]
