from django.contrib.auth import views as auth_views
from django.urls import path
from . import views, governance_views
urlpatterns=[
 path('capacity/balance/',governance_views.capacity_balance,name='capacity_balance'),
 path('capacity/',governance_views.capacity_dashboard,name='capacity_dashboard'),
 path('capacity/priorities/<int:pk>/',governance_views.manage_priority_policy,name='manage_priority_policy'),
 path('capacity/periods/new/',governance_views.manage_allocation_period,name='manage_allocation_period_create'),
 path('capacity/periods/<int:pk>/',governance_views.manage_allocation_period,name='manage_allocation_period_edit'),
 path('capacity/allocations/new/',governance_views.manage_credit_allocation,name='manage_credit_allocation_create'),
 path('capacity/allocations/<int:pk>/',governance_views.manage_credit_allocation,name='manage_credit_allocation_edit'),
 path('capacity/policies/new/',governance_views.manage_approval_policy,name='manage_approval_policy_create'),
 path('capacity/policies/<int:pk>/',governance_views.manage_approval_policy,name='manage_approval_policy_edit'),
 path('capacity/senior/',governance_views.manage_senior_authority,name='manage_senior_authority'),
 path('capacity/senior/assign/',governance_views.assign_senior_authority,name='assign_senior_authority'),
 path('approvals/',governance_views.approval_inbox,name='approval_inbox'),
 path('approvals/<int:pk>/',governance_views.approval_detail,name='approval_detail'),
 path('approvals/<int:pk>/clarify/',governance_views.approval_clarify,name='approval_clarify'),
 path('approvals/steps/<int:pk>/decide/',governance_views.approval_decide,name='approval_decide'),
 path('approvals/attachments/<int:pk>/',governance_views.approval_attachment_download,name='approval_attachment_download'),
 path('control/requests/<int:pk>/approval/',governance_views.provider_approval,name='provider_approval'),
 path('requests/<int:pk>/cancel-approval/',governance_views.cancel_priority_approval,name='cancel_priority_approval'),
 path("appearance/",views.appearance_settings,name="appearance_settings"),path("appearance/logo/",views.brand_logo,name="brand_logo"),
 path("login/",views.PortalLoginView.as_view(),name="login"),path("logout/",auth_views.LogoutView.as_view(),name="logout"),
 path("password/",views.password_change,name="password_change"),
 path("password/done/",auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"),name="password_change_done"),
 path("",views.home,name="home"),path("services/",views.service_hub,name="service_hub"),path("services/departments/<slug:code>/",views.department_landing,name="department_landing"),path("catalog/",views.catalog,name="catalog"),path("catalog/<int:pk>/",views.service_detail,name="service_detail"),
 path("requests/new/<int:service_id>/",views.request_create,name="request_create"),path("requests/",views.my_requests,name="my_requests"),path("drafts/",views.my_requests,name="drafts"),
 path("requests/<int:pk>/",views.request_detail,name="request_detail"),path("requests/<int:pk>/edit/",views.request_edit,name="request_edit"),path("requests/<int:pk>/submit/",views.submit_request,name="submit_request"),path("requests/<int:pk>/message/",views.add_message,name="add_message"),path("requests/<int:pk>/brief/",views.brief_print,name="brief_print"),
 path("attachments/<int:pk>/",views.attachment_download,name="attachment_download"),path("notifications/",views.notifications,name="notifications"),path("notifications/<int:pk>/read/",views.notification_read,name="notification_read"),path("profile/",views.profile,name="profile"),
 path("program/dashboard/",views.program_dashboard,name="program_dashboard"),path("program/requests/",views.demand_requests,name="demand_requests"),path("program/request-project-options/",views.demand_project_options,name="demand_project_options"),
 path("control/programs/",views.manage_programs,name="manage_programs"),path("control/programs/new/",views.manage_program,name="manage_program_create"),path("control/programs/<int:pk>/",views.manage_program_detail,name="manage_program_detail"),path("control/programs/<int:pk>/edit/",views.manage_program,name="manage_program_edit"),path("control/programs/<int:program_pk>/assignments/",views.manage_program_assignment,name="manage_program_assignment"),
 path("control/projects/",views.manage_projects,name="manage_projects"),path("control/projects/new/",views.manage_project,name="manage_project_create"),path("control/projects/<int:pk>/",views.manage_project_detail,name="manage_project_detail"),path("control/projects/<int:pk>/edit/",views.manage_project,name="manage_project_edit"),path("control/projects/<int:project_pk>/assignments/",views.manage_project_assignment,name="manage_project_assignment"),
 path("project/requests/",views.demand_requests,name="project_requests"),
 path("control/",views.control_dashboard,name="control_dashboard"),path("control/requests/",views.control_requests,name="control_requests"),path("control/requests/<int:pk>/",views.control_request_detail,name="control_request_detail"),path("control/requests/<int:pk>/action/",views.control_action,name="control_action"),
 path("control/departments/",views.manage_departments,name="manage_departments"),path("control/departments/new/",views.manage_department_edit,name="manage_department_create"),path("control/departments/<int:pk>/",views.manage_department_detail,name="manage_department_detail"),path("control/departments/<int:pk>/edit/",views.manage_department_edit,name="manage_department_edit"),path("control/departments/<int:pk>/status/",views.manage_department_status,name="manage_department_status"),path("control/departments/<int:pk>/members/",views.manage_department_members,name="manage_department_members"),path("control/departments/<int:department_pk>/families/new/",views.manage_family_edit,name="manage_family_create"),path("control/families/<int:pk>/edit/",views.manage_family_edit,name="manage_family_edit"),path("control/departments/<int:department_pk>/services/new/",views.manage_service_edit,name="manage_service_create"),path("control/services/<int:pk>/edit/",views.manage_service_edit,name="manage_service_edit"),
]
